using Beautiful;
using Microsoft.Practices.EnterpriseLibrary.Data;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using KansaiUtils;
using PoweredSource;
using System;
using static System.Console;
using System.Diagnostics;

namespace UnitTest

{


    [TestClass]
    public class UnitTest4
    {

        public void Debug(string jsonCategory = "", string jsonRole = "", string jsonRoleGroup = "", string jsonIncident = "")
        {
            //'width:100%;height:60px;overflow:visible'
            var sb = new StringBuilder();
            sb.AppendLine("<html> ");
            sb.AppendLine("<body> ");
            sb.AppendLine("<table>");
            sb.AppendLine("<tr>");
            sb.AppendFormat("<td> <textarea cols=\"50\" style='overflow:scroll' rows=\"100\">Category  {0}\r\n{1}</textarea></td>", typeof(RoleCategory).Name, jsonCategory);
            sb.AppendFormat("<td> <textarea cols=\"50\" style='overflow:scroll' rows=\"100\">Role:     {0}\r\n{1}</textarea></td>", typeof(RoleInfo).Name, jsonRole);
            sb.AppendFormat("<td> <textarea cols=\"50\" style='overflow:scroll' rows=\"100\">RoleGroup:{0}\r\n{1}</textarea></td>", typeof(RoleInfo).Name + "Group", jsonRoleGroup);
            sb.AppendFormat("<td> <textarea cols=\"50\" style='overflow:scroll' rows=\"100\">Incident :{0}\r\n{1}</textarea></td>", typeof(IncidentInfo).Name, jsonIncident);
            sb.AppendLine("</tr>");
            sb.AppendLine("</table>");
            sb.AppendLine("</body> ");
            sb.AppendLine("</html> ");
            const string debugJsonPath = "jsondebug.html";
            File.WriteAllText(debugJsonPath, sb.ToString());
            System.Diagnostics.Process.Start(debugJsonPath);       //     Process p = new Process();
                                                                   //     string path = @"Artlisense.py";
                                                                   //     string sArguments = path;
                                                                   //    p.StartInfo.FileName = @"E:\Python36-32\python.exe";
                                                                   ////     p.StartInfo.FileName = "python.exe";
                                                                   //     p.StartInfo.Arguments = sArguments;//python命令的参数
                                                                   //     p.StartInfo.UseShellExecute = false;
                                                                   //     p.StartInfo.RedirectStandardOutput = true;
                                                                   //     p.StartInfo.RedirectStandardInput = true;
                                                                   //     p.StartInfo.RedirectStandardError = true;
                                                                   //     p.StartInfo.CreateNoWindow = true;
                                                                   //     p.Start();
        }  [TestMethod]
        public void callpython()
        {
            Process p = new Process();
            //p.StartInfo.f @"Artlisense.py";
            string sArguments = @"F:\VSProjects\AngelWolf\UnitTest\Artlisense.py";
          
            p.StartInfo.FileName = @"E:\Python36-32\python.exe";
           // p.StartInfo.FileName =  "python.exe";
                                           p.StartInfo.Arguments = sArguments;//python命令的参数
                                        p.StartInfo.UseShellExecute = false;
            p.StartInfo.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardInput = true;
            p.StartInfo.RedirectStandardError = true;
            p.StartInfo.CreateNoWindow = true;
            p.Start();
        }
        [TestMethod]
        public void asdf()
        {
            //python脚本的路径
            string filename = "Artlisense.py";
            //python环境路径
          //  string strArr = @"E:\Python36-32\python.exe";
            string cmd1 = string.Format("{0} {1}", filename, "");
             run_cmd("python.exe", cmd1);

        }

        public string run_cmd(string program, string cmd)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = program;
            start.Arguments = cmd;
            start.UseShellExecute = false;          // Do not use OS shell
            start.CreateNoWindow = true;            // We don‘t need new window
            start.RedirectStandardOutput = true;    // Any output, generated by application will be redirected back
            start.RedirectStandardError = true;     // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string result = process.StandardError.ReadToEnd();
                    if (result == null || result == "")
                    {
                        result = reader.ReadToEnd();
                    }
                    return result;
                }
            }
        }
    }
}
